### ISSUE TITLE
seveal questions about

### ISSUE THREAD

**Issue by aryanna384** [audiofhrozen/motion_dance#4]
Hi, is there any example of data? Is the option 'list' in annot_eval refer to the file of dataset?

**Comment by Fhrozen** [comment]
yes, if you execute `run.sh --stage -1`, it will download the dataset.
the file is located at <root>/local

**Comment by aryanna384** [comment]
thanks for so so so fast reply，I found the URL in win/getdata just after I opened this issue, but I have trouble running with command：
` 
MINGW64 /e/motion_dance-master/local
$ ./run.sh --stage -1
./path.sh: line 11: /e/motion_dance-master/local/tools/venv/bin/activate: No such file or directory
./cmd.sh: line 8: wget: command not found
./cmd.sh: line 13: wget: command not found
./run.sh: line 30: local/parse_options.sh: No such file or directory
`
 so I download it by explorer！

**Comment by Fhrozen** [comment]
There are two problems with your setup.
First, you need to install conda using `cd <root>/tools && Make`
Then, it seems that you have not installed ` wget` on your setup. I will recommend you to check for this file.
Additionally, If you are using Windows OS, I will recommend you to use `<root>/win/run.bat` instead of run.sh.

**Comment by aryanna384** [comment]
Hi, I followed the above instructions, I downloaded the data (still from explorer, because of the Internet,I can't download it from onedrive)  and ran the win\run.bat:
`
----- Exp: s2smc_quat_CNN_initstep_1
stage 0: Preparing training annotations.
'ibt' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
Traceback (most recent call last):
  File "local/annot_eval.py", line 350, in <module>
    main()
  File "local/annot_eval.py", line 157, in main
    databeats = processMarsyas(fn)
  File "local/annot_eval.py", line 71, in processMarsyas
    with open('tmp_marsyas.txt') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'tmp_marsyas.txt'
`
and :
`os.system('ibt -off -o "beats" {} tmp_marsyas.txt'.format(wav_fn))`
what is the command  'ibt' ?
THANKS!

**Comment by Fhrozen** [comment]
ibt is a program to obtain the tempo, it can be obtained by installing marsyas http://marsyas.info/doc/manual/marsyas-user/Building-latest-Marsyas-on-Debian_002fUbuntu.html#Building-latest-Marsyas-on-Debian_002fUbuntu

**Comment by Fhrozen** [comment]
You can install marsyas from https://bintray.com/marsyas/windows/marsyas
